### ISSUE TITLE
"Join Meshes: Selected" joins all meshes ignoring the selection (Blender 4.0)

### ISSUE THREAD

**Issue by Kitsunemimii** [teamneoneko/Cats-Blender-Plugin#34] opened 2024-01-23 13:59 UTC
As the title says, the "Join Meshed: Selected" doesn't work in Blender 4.0

I have just downloaded the newest version from this repo. No outdated version

https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/38310323/6c32408c-9861-450e-b3bb-9a22ce4b7122

**Comment by RinaDev-xyz** [comment] 2024-01-23 14:59
I a little confuse on why this isn't working as I can't see any changes in Blender 4.0 which should cause this issue and looking at the code it should just work, though i having a feeling some of the other changes I made might of broke something, however I have manage to reproduce the issue myself anyway.

I going to look into it and see if I can fix it, however as stated in the welcome page, wiki and on the 4.0 branch, 4.0 is not currently a priority as MMD tools has still not been updated so 4.0 issues are a very low priority for me.

However the Join meshes button are pretty much pointless in cats now since blender version 3.5 and above does a better job these days at joining meshes your just better off pressing ctrl + J instead to join the meshes you want instead or using cats for this. Just make sure vertex groups have the same name and blender will do the rest.

**Comment by Kitsunemimii** [comment] 2024-01-23 19:31
Yeah I'm currently using Ctrl + J but noticed this issue today and wanted to share it with you

**Comment by RinaDev-xyz** [comment] 2024-01-23 19:39
Thanks, will get fix at somepoint though. However the 3.6 version still takes priority at the minute, I will keep this issue open unto it is fixed.

**Comment by RinaDev-xyz** [comment] 2024-01-25 11:42
This issue will be fixed in Version 4.0.2, though this version hasn't been released to the main branch yet as i still testing, you can grab it off the dev branch [here](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/tree/blender-40-dev).

I will close this issue once it's get's released onto the the main branch.

**Comment by RinaDev-xyz** [comment] 2024-01-25 13:45
Fix is now on main branch, re-open if there is any further issues with this issue.

**Closed as completed by RinaDev-xyz** 2024-01-25 13:45 UTC
Labels: bug, Fixed
