### ISSUE TITLE
Blender 4.0 ver tries to downgrade to 3.6

### ISSUE THREAD

**Issue by SkySpnc** [teamneoneko/Cats-Blender-Plugin#33] opened 2024-01-19 20:28 UTC
Titles self explanatory.
![image](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/83870752/9b4bfa89-478c-48e1-a772-2c9f8121c656)

**Comment by RinaDev-xyz** [comment] 2024-01-20 02:29
Hi there, please make sure your using the latest version from [this branch](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/tree/blender-40) as in my testing the update check fails (Which it's meant too on purpose) and I don't get notification at all all, this should be impossible on the latest version as the version checker doesn't point to the releases.

This version number reported should be 4.0.1

![image_2024-01-20_023131167](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/104736380/0dcc9351-cdbc-4e94-b9fd-898390e9a270)

**Comment by RinaDev-xyz** [comment] 2024-01-21 01:04
I am still unable to produce your issue in the latest 4.0 branch version and need further information, as stated before please ensure your using the latest from [this branch ](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/tree/blender-40).

Please note, sometimes if you are using a VPN this can also cause update checks in blender to do this.

If I don't get further information within 7 days I will close this issue.

The following info is needed:
OS:
How did you install blender: Windows Store/ Steam or from official blender website for example.
Cats Plugin version:
What exact version of blender:
How to reproduce this issue:

Thanks!

**Comment by RinaDev-xyz** [comment] 2024-01-24 16:53
Even though it's not been 7 days, no one else is having this issue and author has not responded to my request. Closed due to no contact.

**Closed as not planned by RinaDev-xyz** 2024-01-24 16:53 UTC
Labels: invalid, wontfix, Further Info Needed
