### ISSUE TITLE
Pose to Shape key failing

### ISSUE THREAD

**Issue by Zimmerson** [teamneoneko/Cats-Blender-Plugin#63] opened 2024-03-06 15:34 UTC
Hi, I've tried this for both Blender 3.6 and 4.0 and the same issue persists.

Python: Traceback (most recent call last):
  File "C:\Users\Zimmerson\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-40\tools\armature_manual.py", line 318, in execute
    pose_to_shapekey(name)
  File "C:\Users\Zimmerson\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-40\tools\armature_manual.py", line 288, in pose_to_shapekey
    bpy.ops.mesh.select_all(action='DESELECT')
  File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is incorrect

Could this be fixed?

**Comment by RinaDev-xyz** [comment] 2024-03-06 16:06
Ok, it's working just fine for me and I can't seem to re-produce the issue so i need you to clarify a couple of things.

You are using the latest release for cats which is 4.0.4.3 for blender 4.0?:
Windows version:
The traceback states your using the steam version of blender 4.0, is this correct?:
What model format are you using, e.g fbx, pmx etc:
Please explain the steps on how you got to this issue:

Just giving me an traceback doesn't help as I can't reproduce the issue therefor there could be several things causing this.

**Comment by Zimmerson** [comment] 2024-03-06 16:15
No worries: 

I'm using: Cats-Blender-Plugin-Unofficial4.0.4.3.zip
I'm using Blender 4.0 on Steam, yes.

Model format - Pretty sure it's a .fbx. Currently I've not exported the model as either a fbx, pmx etc. But I'll be re-exporting it eventually as a .fbx. (The .blend file was made by someone else but I'm 99% sure it's fbx.)

Steps:  
Go to CATS -> Quick Access -> Start Pose Mode 
The Selected Armature is called n_root (due to japanese naming convention but I've been able to do this on older versions of blender)

Go To Scene Collection -> Select Skeleton -> Expand -> Select Pose -> Cycle through the bone armature until you reach the correct bones. Scale up the bones you want to the correct size -> Pose To Shape Key.

This then spits out the traceback. 

I'll try it with some other models that are confirmed .FBX - I'll even try exporting it as an .fbx and reimporting and trying the same steps to see if the same issue occurs. 

Happy to provide screenshots if necessary also.

**Comment by RinaDev-xyz** [comment] 2024-03-06 16:20
Can I just check that the model does have meshes and the meshes are inside the armature?

It's also possible it could just be that model (Not been set up correctly or something).

I tested the pose to shapekey on several different models (pmx, blend and fbx's) and can't seem to re-produce this issue so far.

**Comment by Zimmerson** [comment] 2024-03-06 16:30
UPDATE: I think I know the culprit. 

I believe it's the drivers which are set on meshes which activate when you toggle on certain shape keys. At least when I delete the meshes that are linked to the mesh i'm trying to alter, it then works.

**Comment by RinaDev-xyz** [comment] 2024-03-06 16:35
Ah i see, I don't think Cats has ever supported shapekey drivers so that's most likely why and unless something has change in recent versions of Unity, Unity doesn't support blender shapekey drivers as far as I know (Only basic shapekey support).

Therefor unless support for them is popular this isn't a feature cats wills support, however I will try to add a better way of handling this issue, like a error popup telling he user to remove shapekey drivers or something.

**Comment by Zimmerson** [comment] 2024-03-06 16:38
Do you think there's a way there could be a toggle to just "Ignore all drivers" or for it to create the shapekey even if there are drivers there? I don't know how deep this goes with drivers so I apologise if im asking for something unreasonable. I'm not importing these models into Unity, they're more for Final Fantasy XIV (you're probably confused as to why i'm using Cats-Blender-Tools for something not VRChat/Unity related) as I find the quick access tools for Cats invaluable even when i'm not doing things for VR/Unity.

**Comment by RinaDev-xyz** [comment] 2024-03-06 16:41
I will have to look into it, however I don't think we can just "Ignore them" but I not exactly sure how the API works around them so let me get back to you.

**Comment by Zimmerson** [comment] 2024-03-06 16:43
No worries, take your time. For now I can work around this :)

And thanks for your speedy replies, I appreciate that!

**Comment by RinaDev-xyz** [comment] 2024-03-06 17:01
No worries, I was on github anyhow xD.

Also i just pushed a update to the dev build for 4.0, is there any chance you could check it out and see if the update works on that model? I not sure if it will as I think it might throw a other error, but would appreciate if you tested it.

I don't have any models with shapekey drivers myself so can't test it.

**Comment by Zimmerson** [comment] 2024-03-06 20:33
Sure - I'll end up testing it around... 11:30 PM tonight due to current plans 👍

**Comment by RinaDev-xyz** [comment] 2024-03-08 21:08
Hi there!

Did you manage to test this?

Thanks!

**Comment by Zimmerson** [comment] 2024-03-09 01:12
Ack! 

I give me a moment, ill do it now.

Been too busy and tired to test it :(



I presume the 4.0 Dev version is: Cats-Blender-Plugin-Unofficial--blender-40-dev.zip

Update:

Tried it and it didn't work:

Python: Traceback (most recent call last):
  File "C:\Users\Zimmerson\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-40-dev\tools\armature_manual.py", line 336, in execute
    pose_to_shapekey(name)
  File "C:\Users\Zimmerson\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-40-dev\tools\armature_manual.py", line 297, in pose_to_shapekey
    bpy.ops.mesh.select_all(action='DESELECT')
  File "E:\SteamLibrary\steamapps\common\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is incorrect

**Comment by RinaDev-xyz** [comment] 2024-03-09 01:24
Hmm, werid maybe it just does not like drivers on a model what so ever then, as the code added should disable drivers while the operation does it's thing and then re-enable them once the operation is done.

I will have to look into this further I think and try and get a model with drivers to test myself as I think I going to have to debug this. Any suggestions on models would be appreciated.

**Comment by Zimmerson** [comment] 2024-03-09 03:33
No worries - I could send you the DEV kit im working with if need be.

**Comment by RinaDev-xyz** [comment] 2024-03-09 03:36
That would be great if you could as I struggling to find a model myself, if you need to do that privately the best place would be to send it to my email which is hello@yusarina.xyz

**Comment by RinaDev-xyz** [comment] 2024-03-09 05:42
Hi there,

Don't worry about sending me anything I made my own model with drivers and will be trying to fix this issue tomorrow with my own test model.

Thanks!

**Comment by RinaDev-xyz** [comment] 2024-03-10 02:21
Hi there, I done a load of testing with a model I made myself with drivers and a model I found online which had several different shapekey drivers and I not getting the same issue you are. I think this error might be local to very few models and there might just be something very specific on the that model you have which is causing an issue.

Therefor as it seems to be limited it may not be worth fixing this issue unless A: You have multiple models which do it or B: Other users start having similar issues.

The problem I am having is that error isn't really telling me anything.

A other thing is, this could also not be a plugin issue, this could be a blender issue as bpy.ops.mesh.select_all(action='DESELECT') is an internal blender function and this is where it seems to be failing on. 

Now normally the most common reason why this would fail if blender wasn't in edit mode, however the script calls for blender to go into edit mode before the function is called (And if it didn't this would fail all the time not just in this one instance). 

The only other things I can think of which could cause this issue is the following:

1: There is something else on the model which is causing the script to fail.
2: The model has some kind of corrupted or werid complex data (Doubt this)
3: There could be locked or hidden objects in the scene, however these are meant to be unhidden if you used the cats importer.
4: A other plugin you have could be interfering (Doubt this).
5: There are multiple objects in the scene which are not in the main armature (or multiple Armatures) and for some reason the script doesn't like it, however this shouldn't be the case.
5a: If some of the objects relating to the drivers are not in the armature itself this can cause an issue, this is not really a fixable issue and you would have to make sure the objects are the child of the armature first before posing the shapekey.
6: It's a blender bug.

If you manage to find any more information out which could help me trace this issue please feel free to let me know. If might be helpful if you send me an image of how the objects and armature is set up for that model as well.

**Comment by RinaDev-xyz** [comment] 2024-03-12 22:17
Closed as no further information has been given, feel free to re-open if more information can be given.

**Closed as not planned by RinaDev-xyz** 2024-03-12 22:17 UTC
Labels: bug, wontfix
