### ISSUE TITLE
Separating Loose Shapes won't work. "no auto smooth."

### ISSUE THREAD

**Issue by CaramellApll** [teamneoneko/Cats-Blender-Plugin#80] opened 2024-03-30 21:40 UTC
I don't know, I just got this version

**Comment by RinaDev-xyz** [comment] 2024-03-30 21:42
What blender version?
Screenshot of error?
Steps to reproduced?
I need more info then this doesn't work.

**Comment by RinaDev-xyz** [comment] 2024-03-31 08:59
I have tried separated by loose parts on all three blender versions we support and have had no issues.

I have closed this issue as there has been no reply from you and you never provided any context and information in the first place. If your still having this issue and want to provide more info please open a new issue and please ensure you read [this](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/issues/81) before you do.

Thanks!

**Comment by jagrosh** [comment] 2024-06-20 22:04
I am also experiencing this issue. The steps I performed to get the error:
1. Open Blender
2. Import an FBX file via the Blender import (likely FBX-specific)
3. Click "Separate by: Materials" button

When I import via the Cats Import button, I do not get this error. Ideally, this error would not happen regardless of import method.

Blender: 4.1.1
Cats: 4.1.1.4

```
Python: Traceback (most recent call last):
  File "C:\Users\jagrosh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41\tools\armature_manual.py", line 629, in execute
    Common.separate_by_materials(context, obj)
  File "C:\Users\jagrosh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Cats-Blender-Plugin-Unofficial--blender-41\tools\common.py", line 790, in separate_by_materials
    utils.separateByMaterials(mesh)
  File "C:\Users\jagrosh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\utils.py", line 122, in separateByMaterials
  File "C:\Users\jagrosh\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\cats-blender-plugin-0-19-0\extern_tools\mmd_tools_local\utils.py", line 90, in __getCustomNormalKeeper
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
```

**Comment by RinaDev-xyz** [comment] 2024-06-20 22:08
Ermm according to this you have both the old main branch of the official cats installed and also have our unofficial cats installed. 

Please remove the old cats as the Official Cats and Unofficial Cats do not work together. 

Please also ensure you restarted blender between installs as the old cats does not disable itself correctly unto you restart blender.

**Comment by jagrosh** [comment] 2024-06-20 22:17
That solved it; I had removed the old plugin prior to performing this, but I guess it didn't clear out everything. Removing the new Cats, restarting Blender, and adding the new Cats back seems to have solved the problem.

**Comment by RinaDev-xyz** [comment] 2024-06-20 22:19
Yea this is because the old cats doesn't unregister it's classes correctly, therefor when you install our version there a conflict in the classes due to this unto you restart blender. 

As this is solved I will close this issue, if you have any other issue feel free to start a new issue or join our discord. 

Thanks!

**Closed as completed by RinaDev-xyz** 2024-06-20 22:19 UTC
