### ISSUE TITLE
Merge armature giving an error

### ISSUE THREAD

**Issue by Groot0075** [teamneoneko/Cats-Blender-Plugin#139] opened 2024-07-17 19:28 UTC
not much in the description as for some reason every time I try to use the merge armature function and getting a python error for some reason and this has been happening since I updated to the last version of Blender at least and tried both the normal release of the cats too and the dev version. also unsure if this has happened to anyone else or it just me but will provide a screenshot below.

Blender version: 4.2 LTS

Cats Version: 4.2.0.3 and also 4.2.0.4-dev

OSC: current version of Windows 11

Steps to reproduce: all I did was just try and click on merge armature and the error pops up

![Screenshot 2024-07-17 145150](https://github.com/user-attachments/assets/d751ef57-41fe-47a7-84a5-03e26fbc6936)

**Comment by RinaDev-xyz** [comment] 2024-07-17 19:40
Hi there, 

Could you do me a favour and try this in Blender 4.1 to see if you get the same error. 

I think I know what the issue is, but want to make sure this isn't just a Blender 4.2 error. 

Thanks!

**Comment by Groot0075** [comment] 2024-07-17 19:48
just did that funnily enough and yeah works just fine on 4.1 but not 4.2 for whatever reason

**Comment by RinaDev-xyz** [comment] 2024-07-17 19:55
Yea I also able to re-produce the issue on 4.2 but not on 4.1.

It seems that Blender made a change in 4.2 and didn't document it as normal, I have pushed a fix to Blender 4.2 dev, however I may make further changes as it makes the clean shapekey process slower then the Blender 4.1 version, but it should work now.

Once I happy with the changes I will push to 4.2 stable.

**Comment by Groot0075** [comment] 2024-07-17 20:03
you got it and hopefully, it will be smooth sailing and not give you too much trouble

**Comment by Groot0075** [comment] 2024-07-17 21:52
should of asked earlier but was dealing a storm and worrying the power might go out but is it ok to close this for now or keep it open until the next stable release for the unofficial cats tool?

**Comment by RinaDev-xyz** [comment] 2024-07-18 12:08
Just keep it open for now, I will close once it's get's pushed to stabel.

**Comment by Groot0075** [comment] 2024-07-18 17:11
gotcha gotcha

**Comment by RinaDev-xyz** [comment] 2024-07-22 03:36
Fixed in latest release see https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/releases/tag/4.2.1.0 issue now closed.

**Closed as completed by RinaDev-xyz** 2024-07-22 03:36 UTC
Labels: bug, Fixed
