### ISSUE TITLE
Separate by: Loose parts Not working

### ISSUE THREAD

**Issue by KannaKamui6969** [teamneoneko/Cats-Blender-Plugin#64] opened 2024-03-07 07:45 UTC
Hello again, the Separate by loose parts seems to push an error and reset the scene. 
![Capture](https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-/assets/74091179/2c331314-f42d-415c-a48d-cce7a862d6db)
This is the error I receive when trying to separate meshes.

**Comment by RinaDev-xyz** [comment] 2024-03-07 16:41
Hi there, 

I confirmed this issue and will look into it.

Thanks for the report!

**Comment by RinaDev-xyz** [comment] 2024-03-07 16:56
This issue should now be fixed in the dev versions for blender 3.6, 4.0 and 4.1. 

This will be pushed to stable in the next few days. 

The issue was because we were checking for the threshold in the recently re-written remove_doubles component, but honestly this check isn't needed as the plugin set's the threshold not the user, therefor it can't be changed by the user. So I have removed this check as it's pointless. 

Thanks!

**Comment by KannaKamui6969** [comment] 2024-03-08 02:11
Ah okay thank you for the fix!

**Comment by RinaDev-xyz** [comment] 2024-03-09 02:38
Issue Closed as fix now released in Cats version 3.6.6.5 for Blender 3.6 and version 4.0.4.4 for Blender 4.0.

Also released to main branch for Blender 4.1.

**Closed as completed by RinaDev-xyz** 2024-03-09 02:38 UTC
Labels: bug, Fixed
