### ISSUE TITLE
Merge Armature Crash

### ISSUE THREAD

**Issue by GoodOleJimmy** [teamneoneko/Cats-Blender-Plugin#129] opened 2024-06-29 18:02 UTC
I have two characters (two separate armatures). I went through renaming the bones to get them ready to merge. When I click merge armatures (merge bones being the only checked box), Blender just closes.
I tried uninstalling, reinstalling, updating, changing the version, etc. It all does the same thing.

_Blender 3.6.7.
Cats 3.6.7.5_

As far as I know it does this with any two armatures. 
Custom Model Creation 
Only selected Merge All Bones
Click merge armatures.

 I don't see an error anywhere, nor a crash report.

https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-/assets/174206035/9a0eb4c2-bf7b-4b43-a5a9-6715b4ad027a

**Comment by RinaDev-xyz** [comment] 2024-06-29 18:29
Hi there, I am unable to re-produce this issue as I can merge armatures just fine via your method which I have tested on multiple models on both Windows and Linux. 

Please ensure your using the latest Blender version as for 3.6 as 3.6.7 is not the latest, 3.6.13 is the latest for Blender 3.6.

Please confirm what OS you are using and please ensure you are not using the Windows store version of Blender.
Please provide your blender crash logs, on Windows these are normally located C:\Users\[your username]\AppData\Local\Temp and the file will be named something like blender_crash.txt. On linux it be locate in the /temp folder.

**Important:** Blender crash logs can sometimes contain sensitive information, such as the username of your account and what you PC Specs are and etc, if you are worried about this please send them to me via dm on [discord](https://discord.catsblenderplugin.xyz/) or to my email hello@yusarina.xyz instead but if you are not then you can attach them here. (This is more for the people who don't want this info in a public place).

If you just removed the old cats and installed our version please also ensure you restarted Blender. 

Also thank you for following the template!

**Comment by RinaDev-xyz** [comment] 2024-07-04 14:56
Hi there as per our rules I will be closing this issue as you have not replied.

Myself and others are not able to reproduce this issue. If you can provide more information then feel free to reopen.

Thanks

**Closed as completed by RinaDev-xyz** 2024-07-04 14:56 UTC
Labels: wontfix, Further Info Needed
